### ISSUE TITLE
Unable to Use copy and paste Shortcuts on macOS Sequoia 15

### ISSUE THREAD

**Issue by shuwn** [zetxek/osx-menubar-translate#10]
I encountered an issue with the osx-menubar-translate application on macOS Sequoia 15. The application does not support the Command+C and Command+V shortcuts for copy and paste operations. However, other text input functions and keystrokes are working correctly.

Steps to Reproduce:
1. Open osx-menubar-translate on macOS Sequoia 15.
2. Copy text using Command+C at word.
3. Attempt to paste text using Command+V a tosx-menubar-translate  .

Expected Result:
Command+V should paste the copied text.

Actual Result:
Command+V shortcuts do not function as expected.

Additional Information:
- macOS version: Sequoia 15
- Application version: v1.1.1

Suggested Fix:
Review the handling of keyboard shortcuts within the application to ensure compatibility with macOS Sequoia 15.

Thank you for your.

**Comment by zetxek** [comment]
Interesting @shuwn - I don't have a Sequoia Mac to test yet, but I'll see what I can find out.

**Comment by shuwn** [comment]
@zetxek, I need to add that in the Translate Menu, currently, all hotkeys are non-functional except for text input, including Command + A. I believe this is due to macOS Sequoia 15 enhancing security, which requires reconfiguring permissions to listen for global hotkeys.

**Comment by zetxek** [comment]
I've been able to reproduce it (I had not built the app for a while!).

I think that you might be right about the hotkeys. First I thought that could be related with https://bugs.webkit.org/show_bug.cgi?id=173277, but I did a test adding a text field - and same issue.

And as you say - also `cmd + A` fails.

![2024-11-15 22 14 39](https://github.com/user-attachments/assets/8bee7529-a5f3-4740-b68d-f42e3f61c59d)

**Comment by shuwn** [comment]
Sorry, I’m not familiar with Swift macOS app development, nor do I have much knowledge about WebKit. 
I’m afraid I won’t be able to offer much help.

By the way, do you have any recommended learning resources? Thank you!

**Comment by zetxek** [comment]
@shuwn can you check this build? https://github.com/zetxek/osx-menubar-translate/releases/tag/v1.2.0
I have been able to make `cmd + c` work. It had never worked, but I really wanted to make it work 😅 

> By the way, do you have any recommended learning resources for macOS & WebKit development? Thank you!

The Apple developer documentation is quite good: https://developer.apple.com/documentation/
These days with LLMs (Copilot, OpenAI/ChatGPT, Gemini, Claude) they are also quite good at giving a kickstart on learning.

**Comment by shuwn** [comment]
The test record is as follows
![Untitled 3](https://github.com/user-attachments/assets/6924e484-5752-4ba2-ba0c-9e7b452bd96d)

Log file
[Log.txt](https://github.com/user-attachments/files/17794824/Log.txt)

Additionally, this version has an extra issue:
Chinese input does not allow selecting candidate words, as shown in the selection list in the image below.
<img width="659" alt="Snipaste_2024-11-18_13-05-14" src="https://github.com/user-attachments/assets/ac40f502-f09a-4c4a-ad84-7cee586bd67d">

I believe this is a minor issue, so I’m only documenting it here for reference.

**Comment by shuwn** [comment]
In certain apps or under specific conditions, the issue of malfunction still occurs.
![ScreenFlow](https://github.com/user-attachments/assets/19f5ead6-95e4-45ab-8036-16fb9f61252e)
