### ISSUE TITLE
Ideas for enhancement

### ISSUE THREAD

**Issue by feppos0** [zetxek/osx-menubar-translate#2]
Hi! Found your super useful translate app.
I'm new to github so hopefully i'm doing right by creating an issue...

I am travelling a lot so this is so useful for translating, but I have some ideas for enhancements:
1. Keyboard shortcut to access the translate window in menu bar.
2. When the translate window appear - be able to write directly on the left column instead of clicking/selecting it first.
3.  Hide the "google translate" column at the top so the windows begin directly from the translating columns

Thank you so much for this app! 
Have the best day! :D

**Comment by zetxek** [comment]
Thanks for the ideas @feppos0!
Sorry for the delay, as I keep the project in my free time, and when I shared it I didn't even expect anyone to find it useful too. But nice that you like it!

I will create tickets for the 3 enhancement ideas, so we can track them. I cannot promise that eventually I will make them, but as the code is open source, anyone is welcome to implement them :-)

**Comment by zetxek** [comment]
As mentioned @feppos0 , I've created different tickets for improvement ideas. 
That way we can track them individually, and we can also make them happen individually one by one.

I'll close this ticket now - and thanks again for the ideas!
